import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import test from 'node:test';
import { execFileSync } from 'node:child_process';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { atomic, sleep } from '../src/common.mjs';
test('MCP reconnect keeps detached job, typed errors and bounded waits', async t => {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'harness-mcp-'));
  const file = path.join(tmp, 'config.json');
  atomic(file, { harnesses: { pi: { binary: path.resolve('tests/fixtures/fake-harness.mjs'), allow_env: ['FAKE_DELAY'] } } });
  const env = { ...process.env, HARNESS_DELEGATION_DIR: path.join(tmp, 'state'), HARNESS_DELEGATION_CONFIG: file, FAKE_DELAY: '1500' };
  async function open() { const client = new Client({ name: 'test', version: '1' }); await client.connect(new StdioClientTransport({ command: process.execPath, args: [path.resolve('bin/harness-delegate.mjs'), 'mcp'], env, stderr: 'pipe' })); return client; }
  let client = await open();
  t.after(() => client.close());
  assert.equal((await client.listTools()).tools.length, 9);
  const call = async (name, args) => JSON.parse((await client.callTool({ name, arguments: args })).content[0].text);
  const started = await call('task_start', { harness: 'pi', cwd: tmp, task: 'tiny', request_key: 'mcp-start' }); assert.equal(started.ok, true);
  const id = started.data.job_id;
  const wait = await call('task_wait', { job_id: id, timeout_seconds: 0 }); assert.equal(wait.data.terminal, false);
  assert.equal('events' in wait.data, false);
  assert.equal('job_dir' in started.data, false);
  const invalid = await call('task_start', { harness: 'pi', cwd: tmp, task: 'tiny', request_key: 'other', binary: '/bin/sh' }); assert.equal(invalid.ok, false);
  await client.close(); client = await open();
  const repeat = await call('task_start', { harness: 'pi', cwd: tmp, task: 'tiny', request_key: 'mcp-start' }); assert.equal(repeat.data.job_id, id);
  await sleep(1700); const result = await call('task_get', { job_id: id, result: true }); assert.equal(result.data.status, 'completed'); assert.equal(result.data.final_text, 'FAKE_PI_DONE');
  assert.equal('supervisor' in result.data, false);
  const detail = await call('task_get', { job_id: id, result: true, detail: true });
  assert.ok(detail.data.supervisor); assert.equal(detail.data.final_text, result.data.final_text);
  const events = await call('task_read', { job_id: id });
  assert.equal(events.data.events.filter(e => e.type === 'text').map(e => e.data.text).join(''), 'FAKE_PI_DONE');
  const raw = await call('task_read', { job_id: id, detail: true });
  assert.ok(raw.data.events.some(e => e.type === 'text.delta'));
  const cli = (...args) => JSON.parse(execFileSync(process.execPath, ['bin/harness-delegate.mjs', ...args], { env, encoding: 'utf8' })).data;
  assert.deepEqual(cli('result', id), result.data);
  assert.deepEqual(cli('result', id, '--detail'), detail.data);
  assert.deepEqual(cli('read', id), events.data);
  assert.equal('events' in cli('wait', id, '--timeout-seconds', '0'), false);
  assert.ok(cli('wait', id, '--timeout-seconds', '0', '--detail').events.length);
  await client.close(); fs.rmSync(tmp, { recursive: true, force: true });
});
